### ISSUE TITLE
Storybook sample component

### ISSUE THREAD

**Issue by 0fatihyildiz** [Lefineco/Frontend#6]
Sample component should be made for storybook

**Comment by eraygundogmus** [comment]
https://github.com/Lefineco/Frontend/blob/main/src/stories/Button.stories.ts
Already got one here, what do you mean? Could you be more descriptive?

**Comment by 0fatihyildiz** [comment]
there were typescript errors, lastly, I think I opened them for correction, I will assigment myself @eraygundogmus
